#!/usr/bin/env bash
#currently configuring nginx to run as nginx user lol
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
pkill nginx
sudo -u nginx service nginx restart
